bestblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    # take care of ours authentication urls,
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include("members.urls")),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import HomeView, DetailView, AddPostView, UpdatePostView,\
    DeletePostView, AddCategoryView, CategoryView, CategoryListView, LikeView, AddCommentView
app_name = 'blog'

urlpatterns = [
    #post views
    # path('', views.home, name='home'),
    path('', HomeView.as_view(), name='home'),
    path('detail/<int:pk>', DetailView.as_view(), name='detail'),
    path('add_post/', AddPostView.as_view(), name = 'add_post'),
    path('add_category/', AddCategoryView.as_view(), name = 'add_category'),
    path('detail/edit/<int:pk>', UpdatePostView.as_view(), name = 'edit_post'),
    path('detail/<int:pk>/delete', DeletePostView.as_view(), name = 'delete_post'),
    path('category/<str:cats>/', CategoryView, name = 'category'),
    path('category-list', CategoryListView, name= 'category-list'),
    path('like/<int:pk>', LikeView, name = 'like_post'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name='add_comment'),

]

members/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfilePageView, EditProfilePageView, CreateProfilePageView
from django.contrib.auth import views as auth_views
from . import views
app_name = 'members'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name = 'register'),
    path('edit_profile/', UserEditView.as_view(), name = 'edit_profile'),
    # path('password/', auth_views.PasswordChangeView.as_view(template_name = 'registration/change_password.html'))
    path('password/', PasswordsChangeView.as_view(template_name = 'registration/change_password.html')) ,
    path('password_success', views.password_success, name = 'password_success'),
    path('<int:pk>/profile', ShowProfilePageView.as_view(), name = 'show_profile_page'),
    path('<int:pk>/edit_profile_page/', EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page/', CreateProfilePageView.as_view(), name='create_profile_page'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return reverse('blog:detail', args=(str(self.id)))
        # If we are reversing inside a function we can use reverse().
        return reverse('blog:home')


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to='images/profile/')
    website_url = models.CharField(max_length=255, null=True, blank = True)
    facebook_url = models.CharField(max_length=255, null=True, blank=True)
    instagram_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)

    @property
    def get_photo_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url
        else:
            return "/media/blank/user.png"

    def get_absolute_url(self):
        # return reverse('blog:detail', args=(str(self.id)))
        # If we are reversing inside a function we can use reverse().
        return reverse('blog:home')




class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=User)
    body = RichTextField(blank=True, null=True)
    # body = models.TextField()
    date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255, default='coding')
    snippet = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + '|' + str(self.author)

    def get_absolute_url(self):
        # return reverse('blog:detail', args=(str(self.id)))
        # If we are reversing inside a function we can use reverse().
        return reverse('blog:home')

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(User, on_delete=models.CASCADE, default=User)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category, Comment
from .form import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# def home(request):
#     return render(request, 'home.html', {})


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('blog:detail', args=[str(pk)]))

# this is class based views
class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    # ordering = ['-id']
    ordering = ['-date']

    # def post(self, request):
    #     Product.object.create()
#function based views:
    # function productList(request):
    #     products = Products.objects.all()
    #     context = {'products/': products}
    #     return render(request, 'base/product_list.html', context)
# when we utilize class based view in urls needs to be HomeView.as_view()

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context



class DetailView(DetailView):
    model = Post
    template_name = 'detail.html'
    ordering = ['-date']
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(DetailView, self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])

        total_likes = stuff.total_likes()
        context["cat_menu"] = cat_menu
        context["total_likes"] = total_likes
        return context





class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    # fields = ('title', 'body')
    # fields = '__all__'
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(AddPostView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context



class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'
    # fields = '__all__'
    def get_success_url(self):
        # if you are passing 'pk' from 'urls' to 'DeleteView' for company
        # capture that 'pk' as companyid and pass it to 'reverse_lazy()' function
        postid = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk': postid})

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'update_post.html'
    # fields = ['title', 'title_tag', 'body']
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(UpdatePostView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context
    def get_success_url(self):
        # if you are passing 'pk' from 'urls' to 'DeleteView' for company
        # capture that 'pk' as companyid and pass it to 'reverse_lazy()' function
        postid = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk': postid})


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    # If we are using success_url we have to use reverse_lazy().
    success_url = reverse_lazy('blog:home')
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(DeletePostView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context


class AddCategoryView(CreateView):
    model = Category
    # form_class = PostForm
    template_name = 'add_category.html'
    # fields = ('title', 'body')
    fields = '__all__'
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(AddCategoryView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context



# cats in urls
def CategoryView(request, cats):
    category_posts = Post.objects.filter(category = cats.replace('-', ' '))
    return render(request, 'categories.html', {'cats': cats.title().replace('-', ' '), 'category_posts':category_posts})
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(CategoryView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context


def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'category_list.html', {'cat_menu_list':cat_menu_list})

blog/templates/add_category.html
{% extends 'base.html' %}
{% block title %}Create a category post{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<h2> Add category </h2>
<br/><br/>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Add category</button>
</form>
</div>
{% else %}
 You can't add post if you not admin.
{% endif %}


{% endblock %}

blog/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Create a comment{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<h2> Add comment </h2>
<br/><br/>
<div class="form-group">
    <form method="POST"">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Add comment</button>
</form>
{% endif %}

<script>
    var name = "{{ user.id }}";
    document.getElementById("elder").value = name;

</script>
</div>



{% endblock %}

blog/templates/add_post.html
{% extends 'base.html' %}
{% block title %}Create a blog post{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<h2> Add blog post </h2>
<br/><br/>
<div class="form-group">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Post</button>
</form>
</div>

<script>
    var name = "{{ user.id }}";
    document.getElementById("elder").value = name;

</script>

{% else %}
 You can't add post if you not correct user.
{% endif %}


{% endblock %}

blog/templates/categories.html
{% extends 'base.html' %}
{% block content %}

{% if category_posts %}
    <h2>{{ cats }} Category </h2>
    <ul>
    {% for post in category_posts %}

        <li><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
            - {{ post.author.first_name }} {{ post.author.last_name }} - {{ post.date }}
            {% if user.is_authenticated %}<a href="{% url 'blog:edit_post' post.pk %}">Edit</a> <a href="{% url 'blog:delete_post' post.pk %}">Delete</a><br/>{% endif %}
    <br/>
            {{ post.body|slice:":200"|safe }}</li>
    {% endfor %}
    </ul>
{% else %}
    <h1>This page does not exist</h1>
{% endif %}





{% endblock %}

blog/templates/category_list.html
{% extends 'base.html' %}
{% block title %}Blog categories{% endblock %}
{% block content %}

<h1>Blog categories</h1>

    {% for item in cat_menu_list %}
            <h4><a class="dropdown-item" href="{% url 'blog:category' item|slugify %}">   {{ item }} </a></h4>
    {% endfor %}


<br/><br/>
<a href="{% url 'blog:home' %}" class="btn btn-secondary">Back</a>

{% endblock %}

blog/templates/delete_post.html
{% extends 'base.html' %}
{% block title %}Delete a blog post{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <h2> Delete blog post </h2>
    <br/><br/>
    <h3>Delete {{ post.title }}</h3>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <strong>Are you sure?</strong><br/><br/>
            <button class="btn btn-secondary">Delete</button>
    </form>
    </div>
    {% else %}
<!--        i need here error 404 pageeee-->
         You can't delete post if you not correct user.
    {% endif %}
{% else %}
 You can't delete post if you not correct user.
{% endif %}


{% endblock %}

blog/templates/detail.html
{% extends 'base.html' %}
{% block title %}{{post.title_tag}}{% endblock %}
{% block content %}

<h1>{{ post.title }} </h1>
<strong>({{ post.category }})</strong>
{{ post.date }}
<small>By: {{ post.author.first_name }} {{ post.author.last_name }}</small><br/>
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
<a href="{% url 'blog:edit_post' post.pk %}">Edit</a>
<a href="{% url 'blog:delete_post' post.pk %}">Delete</a>
    {% endif %}
{% endif %}
<hr>
<br/>
{% if post.header_image %}
<img src="{{ post.header_image.url }}">
{% endif %}
<br/>
{{ post.body|safe }}


<br/><br/>
<!--<a href="{% url 'blog:home' %}" class="btn btn-secondary">Back</a>-->

<br/><br/>
<hr/>
<br/>
{% if user.is_authenticated %}
<form action="{% url 'blog:like_post' post.pk %}" method="post">
    {% csrf_token %}
    <button id="like", type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">Like</button> -- {{ total_likes }} Likes
</form>
{% else %}
    <a class="btn btn-primary btn-sm" href="{% url 'login' %}">Like</a> -- {{ total_likes }} Likes
{% endif %}
<br/>
<br/>
<hr/>




<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-3">
      <img src="{{ post.author.profile.get_photo_url }}" width=100 height=100>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title">{{post.author.first_name }} {{post.author.last_name }}
            | <a href="{% url 'members:show_profile_page' post.author.profile.id %} ">Profile page</a> </h5>
        <p class="card-text">{{ post.author.profile.bio }}</p>
            {% if post.author.profile.facebook_url %}
          <h5 class="fab fa-facebook"><a target="_blank" href="{{ post.author.profile.facebook_url }}">Facebook</a></h5>
            {% endif %}
            {% if post.author.profile.instagram_url %}
          <h5 "class="fab fa-instagram-square"><a target="_blank" href="{{ post.author.profile.instagram_url }}">Instagram</a></h5>
            {% endif %}
      </div>
    </div>
  </div>
</div>
<br/>
<h1>Comments...</h1>
<br/>
{% if not post.comments.all %}
	No Comments Yet...<a href="{% url 'blog:add_comment' post.pk %}">Add One</a>
{% else %}
{% if user.is_authenticated %}
<a href="{% url 'blog:add_comment' post.pk %}">Add Comment</a>
{% else %}
    <h5> Moras se <a href="{% url 'login' %}">ulogovati</a> kako bi postavio komentar. </h5>
{% endif %}
<br/><br/>

	{% for comment in post.comments.all %}
		<strong>

			{{ comment.name.first_name }} {{ comment.name.last_name }} |
			{{ comment.date }}

		</strong>
		<br/>
		{{ comment.body }}
		<br/><br/>


	{% endfor %}

{% endif %}
<br/>


{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}
{% block content %}


<h2> Post </h2>
<ul>

{% for post in object_list %}
<!--    <li><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>-->
<!--        <strong><a href="{% url 'blog:category' post.category|slugify %}">({{ post.category }})</a> </strong>-->
<!--        - {{ post.author.first_name }} {{ post.author.last_name }} - {{ post.date }}-->
<!--        {% if user.is_authenticated %}-->
<!--            {% if user.id == post.author.id %}-->
<!--        <a href="{% url 'blog:edit_post' post.pk %}">Edit</a>-->
<!--        <a href="{% url 'blog:delete_post' post.pk %}">Delete</a><br/>-->
<!--            {% endif %}-->
<!--        {% endif %}-->
<!--<br/>-->
<!--        {{ post.snippet }}-->
<!--        </li>-->
    <div class="card mb-3" style="max-width: 540px;" <a href="{% url 'blog:detail' post.pk %}">
  <div class="row g-0">
    <div class="col-md-4">
      {% if post.header_image %}
        <img width="100", height="100"  src="{{ post.header_image.url }}">
      {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
          <h5 class="card-title"><a style="text-decoration:none" href="{% url 'blog:detail' post.pk %}">{{ post.title }} </a> -  {{ post.author.first_name }} {{ post.author.last_name }}</h5>
        <p class="card-text">{{ post.snippet }}</p>
        <p class="card-text"><small class="text-muted">{{ post.date }}</small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

</ul>


{% endblock %}

blog/templates/update_post.html
{% extends 'base.html' %}
{% block title %}Edit a blog post{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
        <h2> Edit blog post </h2>
        <br/><br/>
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-secondary">Update</button>
        </form>
        </div>
    {% else %}
<!--        i need here error 404 pageeee-->
        You can't delete post if you not correct user.
    {% endif %}
{% else %}
You can't delete post if you not correct user.
{% endif %}


{% endblock %}